name: Bypass
description: Describe a bypass you noticed
title: "Bypass | "
labels: ["Bypass"]

assignees:
  - micartey

body:
  - type: textarea
    id: general
    attributes:
      label: "Information"
      description: |
        What kind of bypass did you find?
        What are the advantages?
    validations:
      required: true

  - type: textarea
    id: client
    attributes:
      label: "Client"
      description: |
        Please provide a link to the client
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: "Cardinal Version"
      description: |
        What version of cardinal are you running?
        Please provide the full version qualifier (you can get it by executing /cac)
    validations:
      required: true

  - type: textarea
    id: spigot
    attributes:
      label: "Spigot Version"
      description: |
        What version of minecarft are you running?
        Are you using a specific vendor?
    validations:
      required: true


  - type: textarea
    id: video
    attributes:
      label: "Video"
      description: |
        Please upload a video of the bypass
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional information"
    validations:
      required: false