---
name: False Positive
about: Describe a false positive
title: 'False Positive | '
labels: False Positive
assignees: Clientastisch

---

How do you trigger the false positive? Describe it here


Verbose Message



Cardinal Version: 

Spigot Version:

> **Attached Video  (Required)**


name: False Positive
description: Describe a false positive
title: "False Positive | "
labels: ["False Positive"]

assignees: ["micartey"]

body:
  - type: textarea
    id: 1
    attributes:
      label: "Information"
      description: |
        How do you trigger the false positive?
        Describe it as good as possible
    validations:
      required: true

  - type: textarea
    id: 2
    attributes:
      label: "Verbose Message"
      description: |
        What are you flagged for?
        What message is being displayed?
    validations:
      required: true

  - type: textarea
    id: 3
    attributes:
      label: "Cardinal Version"
      description: |
        What version of cardinal are you running?
        Please provide the full version qualifier (you can get it by executing /cac)
    validations:
      required: true

  - type: textarea
    id: 4
    attributes:
      label: "Spigot Version"
      description: |
        What version of minecarft are you running?
        Are you using a specific vendor?
    validations:
      required: true

  - type: textarea
    id: 5
    attributes:
      label: "Video"
      description: |
        Please upload a video of you reproducing the false positive
    validations:
      required: true


  - type: textarea
    id: 6
    attributes:
      label: "Additional information"
    validations:
      required: false